[package]
name = "fixed32"
version = "0.0.18"
edition = "2024"
license = "MIT"
description = "Fixed Point types"
repository = "https://github.com/piot/fixed32-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
